# Generated by Django 3.0.1 on 2019-12-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pointslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointslog',
            old_name='user_id',
            new_name='user',
        ),
    ]
