# Generated by Django 3.0.1 on 2019-12-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_order_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Menu')),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='merchants.Merchant')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order_id'], name='order_order_order_i_2ede3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order_id', 'menu_id')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='order_order_user_id_e527b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('id', 'user_id')},
        ),
    ]
