# Generated by Django 3.0.1 on 2020-01-04 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='merchant_id',
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
