# Generated by Django 3.0.1 on 2020-01-11 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
        ('order', '0002_auto_20200111_0745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order_id', 'menu_id')},
        ),
    ]
