# Generated by Django 3.0.1 on 2020-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200111_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
