# Generated by Django 3.0.1 on 2019-12-25 13:41
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=24, unique=True)),
                ('forced_closing', models.BooleanField(default=True)),
                ('business_day', models.PositiveSmallIntegerField(null=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('country_iso', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=64)),
                ('detail_address', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]