# Generated by Django 3.0.1 on 2020-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20200112_1344'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menu',
            name='merchants_m_merchan_939bc8_idx',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='last_updated_time',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['merchant_id', 'out_of_stock'], name='merchants_m_merchan_2d813c_idx'),
        ),
    ]
