# Generated by Django 3.0.1 on 2020-01-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_auto_20200124_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='original_price',
        ),
    ]
