# Generated by Django 3.0.1 on 2020-01-25 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0004_auto_20200124_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='admin_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
